server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  absolute_redirect off;

  location /swagger {
    try_files $uri $uri/index.html /swagger/index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
